kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-csi-good
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
