apiVersion: v1
kind: Pod
metadata:
  name: pass-example
spec:
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/nanoserver:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
    securityContext:
      windowsOptions:
        runAsUserName: "ContainerUser" # detects this field
  nodeSelector:
    "kubernetes.io/os": windows
