apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-container-disallowed-capabilities
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      # Assuming assignment uses the following:
      capabilities:
        add: ["allowedcapability"]
  - name: image-exclude
    image: exception.azurecr.io/exception:1.0.0 # bypassed by the image exclusion parameter
    securityContext:
      # Assuming assignment uses the following:
      capabilities:
        add: ["blockedcapability"]
  initContainers:
  - name: container-exclude # bypassed by the container exclusion parameter
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      # Assuming assignment uses the following:
      capabilities:
        add: ["blockedcapability"]
