apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/container1: unconfined
  labels:
    app: scenario-runtime-default-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
