apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-container-allowed-images
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/allowed:v1.0.0 # detects this field
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: my-secret