apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  labels:
    app: scenario-range-without-max
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 150
    fsGroup: 150
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
      securityContext:
        runAsUser: 150
        runAsGroup: 150
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
