apiVersion: v1
kind: Pod
metadata:
  name: violation-example
  labels:
    app: scenario-read-only-root-filesystem-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    securityContext:
      readOnlyRootFilesystem: false
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
