apiVersion: v1
kind: Pod
metadata:
  name: violation-memory-limit
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/aks/policy/example:v1.0.0
    resources:
      limits:
        cpu: 100m
        memory: 2000M 