apiVersion: v1
kind: Pod
metadata:
  name: pass-example
  namespace: default
  annotations:
    azuredefender.io/containers.vulnerability.scan.info: "{\"containers\":[{\"name\":\"testContainer\",\"image\":{\"name\":\"tomer.azurecr.io/core/app:4.6\",\"digest\":\"sha256:4a\"},\"scanStatus\":\"healthyScan\",\"scanFindings\":[]}]}"
spec:
  containers:
    - name: container1
      image: mcr.microsoft.com/aks/policy/example:v1.0.0
