apiVersion: v1
kind: Pod
metadata:
  name: pass-windows
  labels:
    app: scenario-forbid-kernel
spec:
  nodeSelector:
    kubernetes.io/os: windows # will bypass windows containers
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
  securityContext:
    sysctls:
    - name: kernel.msgmax
      value: "65536"
